# Generated by Django 2.1.3 on 2019-02-25 18:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='data_gin'),
        ),
    ]
