# Generated by Django 2.1.3 on 2018-11-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feedback', '0002_customerfeedbackimportersettings_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
        migrations.RenameField(
            model_name='featurerequest',
            old_name='problem',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='featurerequest',
            name='solution',
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='effort',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=30),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=30),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='state',
            field=models.CharField(choices=[('UNTRIAGED', 'Untriaged'), ('UNDER_CONSIDERATION', 'Under Consideration'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('SHIPPED', 'Shipped'), ('WONT_DO', "Won't do")], default='UNDER_CONSIDERATION', max_length=30),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='themes',
            field=models.ManyToManyField(to='feedback.Theme'),
        ),
    ]
