# Generated by Django 2.1.3 on 2018-11-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20181123_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='effort',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=30),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=30),
        ),
    ]
