# Generated by Django 2.1.3 on 2019-01-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feedback', '0006_auto_20181130_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackimportersettings',
            name='account_id',
            field=models.CharField(default='fixme', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('EXISTING', 'Paying'), ('CHURNED', 'Churned'), ('LOST_DEAL', 'Lost deal'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='customerfeedbackimportersettings',
            name='webhook_secret',
        ),
        migrations.AlterUniqueTogether(
            name='customerfeedbackimportersettings',
            unique_together={('importer', 'customer', 'account_id')},
        ),
    ]
