# Generated by Django 2.1.3 on 2019-01-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20190122_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='themes',
            field=models.ManyToManyField(blank=True, to='feedback.Theme'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CHURNED', 'Churned'), ('LOST DEAL', 'Lost deal'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
