# Generated by Django 2.1.3 on 2019-02-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20190124_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CHURNED', 'Churned'), ('LOST DEAL', 'Lost deal'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='remote_id',
        ),
    ]
