# Generated by Django 2.1.3 on 2019-02-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20190201_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackimportersettings',
            name='webhook_secret',
            field=models.CharField(max_length=255, default=""),
        ),
    ]
