# Generated by Django 2.1.3 on 2019-02-06 22:38
import uuid
from django.db import migrations


def set_webhook_secrets(apps, schema_editor):
    CustomerFeedbackImporterSettings = apps.get_model('feedback', 'CustomerFeedbackImporterSettings')
    for cfis in CustomerFeedbackImporterSettings.objects.filter(webhook_secret=""):
        cfis.webhook_secret = str(uuid.uuid4())
        cfis.save()

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_add_webhook_secret_to_cfis'),
    ]

    operations = [
        migrations.RunPython(set_webhook_secrets),
    ]
