# Generated by Django 2.1.3 on 2019-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_set_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedbackimportersettings',
            name='account_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='customerfeedbackimportersettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customerfeedbackimportersettings',
            name='webhook_secret',
            field=models.CharField(default='41848805-9459-4b67-a095-29dc1c9a3457', max_length=255, unique=True),
        ),
    ]
