# Generated by Django 2.1.3 on 2019-02-12 00:47

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_auto_20190206_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedbackimportersettings',
            name='webhook_secret',
            field=models.CharField(default=feedback.models.generate_webhook_secret, max_length=255, unique=True),
        ),
    ]
