# Generated by Django 2.1.3 on 2019-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_auto_20190212_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
