# Generated by Django 2.1.3 on 2019-02-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_auto_20190214_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CHURNED', 'Churned'), ('LOST DEAL', 'Lost deal'), ('INTERNAL', 'Internal'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
