# Generated by Django 2.1.3 on 2019-02-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_auto_20190222_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CHURNED', 'Churned'), ('INTERNAL', 'Internal'), ('LOST DEAL', 'Lost deal'), ('PROSPECT', 'Prospect'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
