# Generated by Django 2.1.3 on 2019-03-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_auto_20190226_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('ACTIVE', 'Active customer'), ('CHURNED', 'Churned customer'), ('INTERNAL', 'Internal user'), ('LOST DEAL', 'Lost deal'), ('PROSPECT', 'Prospect'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appaccounts.AppUser'),
        ),
    ]
