# Generated by Django 2.1.3 on 2019-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_auto_20190319_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source_username',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
