# Generated by Django 2.1.3 on 2019-04-26 19:54

from django.db import migrations

def fix_module_paths(apps, schema_editor):
    FeedbackImporter = apps.get_model('feedback', 'FeedbackImporter')

    FeedbackImporter.objects.update_or_create(name='Intercom', defaults={
        'module': 'integrations.intercom.importers.IntercomFeedbackImporter'
    })
    FeedbackImporter.objects.update_or_create(name='Segment', defaults={
        'module': 'integrations.segment.importers.SegmentFeedbackImporter'
    })

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_feedback_source_username'),
    ]

    operations = [
        migrations.RunPython(fix_module_paths),
    ]
