# Generated by Django 2.1.3 on 2019-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_change_feedback_importer_module_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackimportersettings',
            name='feedback_tag_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
