# Generated by Django 2.1.3 on 2019-06-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_customerfeedbackimportersettings_feedback_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackimportersettings',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
