# Generated by Django 2.1.3 on 2019-09-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_featurerequest_import_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='themes',
            field=models.ManyToManyField(blank=True, to='feedback.Theme'),
        ),
    ]
