# Generated by Django 2.1.3 on 2019-09-19 18:22

from django.db import migrations, models

def fix_effort_and_priority_values(apps, schema_editor):
    FeatureRequest = apps.get_model('feedback', 'FeatureRequest')
    
    FeatureRequest.objects.filter(effort='LOW').update(effort='1_LOW')
    FeatureRequest.objects.filter(effort='MEDIUM').update(effort='2_MEDIUM')
    FeatureRequest.objects.filter(effort='HIGH').update(effort='3_HIGH')

    FeatureRequest.objects.filter(priority='LOW').update(priority='1_LOW')
    FeatureRequest.objects.filter(priority='MEDIUM').update(priority='2_MEDIUM')
    FeatureRequest.objects.filter(priority='HIGH').update(priority='3_HIGH')

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0025_feedback_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='effort',
            field=models.CharField(blank=True, choices=[('1_LOW', 'Low'), ('2_MEDIUM', 'Medium'), ('3_HIGH', 'High')], max_length=30),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.CharField(blank=True, choices=[('1_LOW', 'Low'), ('2_MEDIUM', 'Medium'), ('3_HIGH', 'High')], max_length=30),
        ),
        migrations.RunPython(fix_effort_and_priority_values),
    ]
