# Generated by Django 2.1.3 on 2019-09-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0026_auto_20190919_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['title']},
        ),
    ]
