# Generated by Django 2.1.3 on 2019-10-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191004_0011'),
        ('feedback', '0029_auto_20191001_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('customer', 'title')},
        ),
    ]
