# Generated by Django 2.1.3 on 2019-10-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191004_0011'),
        ('appaccounts', '0016_auto_20190923_1929'),
        ('feedback', '0031_auto_20191011_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFromRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_feedback_type', models.CharField(choices=[('ACTIVE', 'Active customer'), ('CHURNED', 'Churned customer'), ('INTERNAL', 'Internal user'), ('LOST DEAL', 'Lost deal'), ('PROSPECT', 'Prospect'), ('OTHER', 'Other')], max_length=30)),
                ('attribute_value_trigger', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('filterable_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appaccounts.FilterableAttribute')),
            ],
        ),
    ]
