# Generated by Django 2.1.3 on 2019-10-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0031_feedbackfromrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackfromrule',
            name='filterable_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appaccounts.FilterableAttribute'),
        ),
    ]
