# Generated by Django 2.1.3 on 2019-10-22 22:00

from django.db import migrations, models

def set_default_shipped_at(apps, schema_editor):
    FeatureRequest = apps.get_model('feedback', 'FeatureRequest')
    for fr in FeatureRequest.objects.filter(state='SHIPPED'):
        if fr.shipped_at == None:
            fr.shipped_at = fr.updated
            fr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0032_auto_20191011_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_default_shipped_at),
    ]
