# Generated by Django 2.1.3 on 2020-02-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0034_feedbacktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='notified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='state',
            field=models.CharField(choices=[('UNTRIAGED', 'Untriaged'), ('UNDER_CONSIDERATION', 'Under Consideration'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('SHIPPED', 'Shipped'), ('CUSTOMER_NOTIFIED', 'Customer Notified'), ('WONT_DO', "Won't do")], default='UNTRIAGED', max_length=30),
        ),
    ]
