# Generated by Django 2.1.3 on 2019-01-24 18:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190124_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='whitelisted_domain',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True, validators=[accounts.models.validate_domain]),
        ),
    ]
