# Generated by Django 2.1.3 on 2019-03-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190124_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_feedback_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
