# Generated by Django 2.1.3 on 2019-03-19 22:10
import string
import secrets

from django.db import migrations

def set_create_feedback_email(apps, schema_editor):

    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        # Why is this code dupped? See here:
        # https://stackoverflow.com/questions/28777338/django-migrations-runpython-not-able-to-call-model-methods/37685925#37685925
        alphabet = string.ascii_letters + string.digits
        secret = ''.join(secrets.choice(alphabet) for i in range(10))
        user.create_feedback_email = f"{secret}@mg.savio.io"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_create_feedback_email'),
    ]

    operations = [
        migrations.RunPython(set_create_feedback_email),
    ]
