# Generated by Django 2.1.3 on 2019-03-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_create_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_feedback_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
