# Generated by Django 2.1.3 on 2019-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190319_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('SUBMITTER', 'Submitter')], default='OWNER', max_length=30),
            preserve_default=False,
        ),
    ]
