# Generated by Django 2.1.3 on 2019-08-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_make_create_feedback_email_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='submitters_can_create_features',
            field=models.BooleanField(default=True),
        ),
    ]
