# Generated by Django 2.1.3 on 2019-10-03 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_statusemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusemailsettings',
            name='first_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statusemailsettings',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
