# Generated by Django 2.1.3 on 2019-10-04 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191003_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusemailsettings',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
