# Generated by Django 2.1.3 on 2020-02-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_featurerequestnotificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequestnotificationsettings',
            name='template',
            field=models.TextField(blank=True, default="Hi {first_name},\n\nJust a heads up - you asked for a feature, and we built it.\n\n[Insert more about the Feature here]\n\nThanks for the request and keep 'em coming - we're always listening.\n\nCheers,\n\n[Insert your name]"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('plan_Ek0Ns9AhiBtR1o', 'Early Adopter - $20/user per month'), ('plan_GgYpcKU6ncOBVe', 'Small - $49/user per month'), ('plan_Gh1Ya0ebnwkY54', 'Medium - $99/user per month')], max_length=255),
        ),
    ]
