# Generated by Django 2.1.3 on 2020-03-19 15:58

from django.db import migrations

def populate_is_per_seat_plan(apps, schema_editor):
    Subscription = apps.get_model('accounts', 'Subscription')
    for sub in Subscription.objects.all():
        sub.is_per_seat_plan = True
        sub.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_subscription_is_per_seat_plan'),
    ]

    operations = [
        migrations.RunPython(populate_is_per_seat_plan),
    ]
