# Generated by Django 2.1.3 on 2020-03-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_populate_is_per_seat_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_per_seat_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('plan_GwSV9PWY04hZ93', 'Tiered pricing'), ('plan_Ek0Ns9AhiBtR1o', 'Early Adopter - $20/user per month'), ('plan_GgYpcKU6ncOBVe', 'Small - $49/user per month'), ('plan_Gh1Ya0ebnwkY54', 'Medium - $99/user per month')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
