# Generated by Django 2.1.3 on 2020-03-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_subscription_upcoming_mrr_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='upcoming_mrr_amount',
            new_name='next_mrr_payment',
        ),
    ]
