# Generated by Django 2.1.3 on 2020-04-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_feedbacktriagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('TASK_CREATE_FEEDBACK', 'TASK_CREATE_FEEDBACK'), ('TASK_CREATE_FEATURE_REQUEST', 'TASK_CREATE_FEATURE_REQUEST'), ('TASK_TRIAGE_FEEDBACK', 'TASK_TRIAGE_FEEDBACK'), ('TASK_CONNECT_HELP_DESK', 'TASK_CONNECT_HELP_DESK')], max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
    ]
