# Generated by Django 2.1.3 on 2020-04-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_onboardingtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingtask',
            name='task_type',
            field=models.CharField(choices=[('TASK_CREATE_VAULT', 'TASK_CREATE_VAULT'), ('TASK_CREATE_FEEDBACK', 'TASK_CREATE_FEEDBACK'), ('TASK_CREATE_FEATURE_REQUEST', 'TASK_CREATE_FEATURE_REQUEST'), ('TASK_TRIAGE_FEEDBACK', 'TASK_TRIAGE_FEEDBACK'), ('TASK_CONNECT_HELP_DESK', 'TASK_CONNECT_HELP_DESK'), ('TASK_SUBMIT_FEEDBACK_VIA_HELP_DESK', 'TASK_SUBMIT_FEEDBACK_VIA_HELP_DESK'), ('TASK_CREATE_FEEDBACK_CE', 'TASK_CREATE_FEEDBACK_CE'), ('TASK_CLOSE_THE_LOOP', 'TASK_CLOSE_THE_LOOP')], max_length=255),
        ),
    ]
