# Generated by Django 2.1.3 on 2020-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_auto_20200528_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
