# Generated by Django 2.1.3 on 2020-06-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_auto_20200527_1321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("plan_GwSV9PWY04hZ93", "Tiered pricing"),
                    ("plan_Ek0Ns9AhiBtR1o", "Early Adopter - $20/user per month"),
                    ("plan_GgYpcKU6ncOBVe", "Small - $49/user per month"),
                    ("plan_Gh1Ya0ebnwkY54", "Medium - $99/user per month"),
                    ("price_1GvX9RCZ3jbVsfoGU340ipi7", "Free for 1 user"),
                    ("price_1GvX9SCZ3jbVsfoGrFIJKBIl", "SMB - $25/m for up to 3 users"),
                    (
                        "price_1GvX9RCZ3jbVsfoGo20C19UN",
                        "Growth - $49/m for unlimited users",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
