# Generated by Django 2.1.3 on 2020-06-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_auto_20200618_2337"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("per_seat", "Per Seat"),
                    ("usage_tiered", "Usage Tiered"),
                    ("feature_tiered", "Feature Tiered"),
                ],
                default="feature_tiered",
                max_length=30,
            ),
        ),
    ]
