# Generated by Django 2.1.3 on 2020-06-18 23:40

from django.db import migrations


def populate_plan_type(apps, schema_editor):
    Subscription = apps.get_model("accounts", "Subscription")
    for sub in Subscription.objects.all():
        if sub.is_per_seat_plan is True:
            sub.plan_type = "per_seat"
        else:
            sub.plan_type = "usage_tiered"

        sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_subscription_plan_type"),
    ]

    operations = [
        migrations.RunPython(populate_plan_type),
    ]
