# Generated by Django 2.1.3 on 2020-06-26 23:40

from django.db import migrations


def fix_dev_plan_id(apps, schema_editor):
    Subscription = apps.get_model("accounts", "Subscription")
    for sub in Subscription.objects.all():
        if sub.plan == "plan_Ek0Ns9AhiBtR1o":
            sub.plan = "plan_El2pYaCzTgKQSi"
            sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_auto_20200624_1255"),
    ]

    operations = [
        migrations.RunPython(fix_dev_plan_id),
    ]
