# Generated by Django 2.1.3 on 2020-07-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("accounts", "0032_auto_20200709_2339"),
        ("accounts", "0033_auto_20200709_2346"),
    ]

    dependencies = [
        ("accounts", "0031_fix_dev_plan_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="first_landing_page",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="first_referer",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_landing_page",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_referer",
            field=models.TextField(null=True),
        ),
    ]
