# Generated by Django 2.1.3 on 2020-10-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="subscription",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.Subscription",
            ),
        ),
    ]
