# Generated by Django 2.1.3 on 2019-04-16 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_add_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_bot_user_id', models.CharField(blank=True, max_length=255)),
                ('slack_bot_token', models.CharField(blank=True, max_length=255)),
                ('slack_team_name', models.CharField(blank=True, max_length=255)),
                ('slack_team_id', models.CharField(blank=True, max_length=255)),
                ('slack_feedback_channel_name', models.CharField(blank=True, max_length=255)),
                ('slack_feedback_channel_id', models.CharField(blank=True, max_length=255)),
                ('slack_access_token', models.CharField(blank=True, max_length=255)),
                ('slack_user_id', models.CharField(blank=True, max_length=255)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_settings', to='accounts.Customer')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
