# Generated by Django 2.1.3 on 2019-04-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slacksettings',
            old_name='slack_access_token',
            new_name='slack_user_access_token',
        ),
    ]
