# Generated by Django 2.1.3 on 2018-11-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcompany',
            name='internal_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appuser',
            name='internal_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
