# Generated by Django 2.1.3 on 2018-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0002_auto_20181116_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
