# Generated by Django 2.1.3 on 2019-02-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0004_auto_20190124_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
