# Generated by Django 2.1.3 on 2019-02-12 00:58

from django.db import migrations

def null_out_internal_ids(apps, schema_editor):
    AppUser = apps.get_model('appaccounts', 'AppUser')
    AppUser.objects.filter(internal_id="").update(internal_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0006_auto_20190212_0057'),
    ]

    operations = [
        migrations.RunPython(null_out_internal_ids),
    ]
