# Generated by Django 2.1.3 on 2019-02-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190124_1825'),
        ('appaccounts', '0007_auto_20190212_0058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appuser',
            unique_together={('customer', 'internal_id'), ('customer', 'remote_id'), ('customer', 'email')},
        ),
    ]
