# Generated by Django 2.1.3 on 2019-02-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0008_auto_20190212_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
