# Generated by Django 2.1.3 on 2019-02-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0009_auto_20190212_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcompany',
            name='internal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appcompany',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
