# Generated by Django 2.1.3 on 2019-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0010_auto_20190212_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcompany',
            name='monthly_spend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
