# Generated by Django 2.1.3 on 2019-02-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190124_1825'),
        ('appaccounts', '0011_auto_20190214_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appcompany',
            unique_together={('customer', 'internal_id'), ('customer', 'remote_id')},
        ),
    ]
