# Generated by Django 2.1.3 on 2019-03-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0012_auto_20190214_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
