# Generated by Django 2.1.3 on 2019-05-03 21:35

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0013_auto_20190319_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcompany',
            name='filterable_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='appuser',
            name='filterable_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='appcompany',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filterable_attributes'], name='appcompany_fa_gin'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filterable_attributes'], name='appuser_fa_gin'),
        ),
    ]
