# Generated by Django 2.1.3 on 2020-07-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appaccounts", "0016_auto_20190923_1929"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            "DROP EXTENSION IF EXISTS pg_trgm",
        ),
        migrations.RunSQL(
            "CREATE INDEX accounts_appuser_name_trigram ON appaccounts_appuser USING gin (UPPER(name) gin_trgm_ops);",
            "DROP INDEX accounts_appuser_name_trigram",
        ),
        migrations.RunSQL(
            "CREATE INDEX accounts_appuser_email_trigram ON appaccounts_appuser USING gin (UPPER(email) gin_trgm_ops);",
            "DROP INDEX accounts_appuser_email_trigram",
        ),
    ]
